# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Create Release

on:
  push:
    #    branches: [ "main" ]
    #  pull_request:
    #    branches: [ "main" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      - name: Zip Files
        run: zip -r ${{ secrets.ReleaseZipName }}.zip ./dist

      - name: Create Release and Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }}
          "${{ secrets.ReleaseZipName }}.zip"
          --generate-notes
